// Code generated by ent, DO NOT EDIT.

package department

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrganizationKey holds the string denoting the organization_key field in the database.
	FieldOrganizationKey = "organization_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeAuthorizedUsers holds the string denoting the authorized_users edge name in mutations.
	EdgeAuthorizedUsers = "authorized_users"
	// EdgeAccessGrants holds the string denoting the access_grants edge name in mutations.
	EdgeAccessGrants = "access_grants"
	// Table holds the table name of the department in the database.
	Table = "departments"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "users"
	// MembersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	MembersInverseTable = "users"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "department_id"
	// AuthorizedUsersTable is the table that holds the authorized_users relation/edge. The primary key declared below.
	AuthorizedUsersTable = "department_access_grants"
	// AuthorizedUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorizedUsersInverseTable = "users"
	// AccessGrantsTable is the table that holds the access_grants relation/edge.
	AccessGrantsTable = "department_access_grants"
	// AccessGrantsInverseTable is the table name for the DepartmentAccessGrant entity.
	// It exists in this package in order to avoid circular dependency with the "departmentaccessgrant" package.
	AccessGrantsInverseTable = "department_access_grants"
	// AccessGrantsColumn is the table column denoting the access_grants relation/edge.
	AccessGrantsColumn = "department_id"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrganizationKey,
	FieldName,
	FieldStatus,
	FieldSortOrder,
	FieldVersion,
}

var (
	// AuthorizedUsersPrimaryKey and AuthorizedUsersColumn2 are the table columns denoting the
	// primary key for the authorized_users relation (M2M).
	AuthorizedUsersPrimaryKey = []string{"user_id", "department_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OrganizationKeyValidator is a validator for the "organization_key" field. It is called by the builders before save.
	OrganizationKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
)

// OrderOption defines the ordering options for the Department queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationKey orders the results by the organization_key field.
func ByOrganizationKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthorizedUsersCount orders the results by authorized_users count.
func ByAuthorizedUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthorizedUsersStep(), opts...)
	}
}

// ByAuthorizedUsers orders the results by authorized_users terms.
func ByAuthorizedUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorizedUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccessGrantsCount orders the results by access_grants count.
func ByAccessGrantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccessGrantsStep(), opts...)
	}
}

// ByAccessGrants orders the results by access_grants terms.
func ByAccessGrants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccessGrantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newAuthorizedUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorizedUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, AuthorizedUsersTable, AuthorizedUsersPrimaryKey...),
	)
}
func newAccessGrantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccessGrantsInverseTable, AccessGrantsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, AccessGrantsTable, AccessGrantsColumn),
	)
}
