// Code generated by ent, DO NOT EDIT.

package departmentaccessgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldUserID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldDepartmentID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, DepartmentColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := newDepartmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, CreatorColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DepartmentAccessGrant) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DepartmentAccessGrant) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DepartmentAccessGrant) predicate.DepartmentAccessGrant {
	return predicate.DepartmentAccessGrant(sql.NotPredicates(p))
}
