// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/departmentaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DepartmentAccessGrantCreate is the builder for creating a DepartmentAccessGrant entity.
type DepartmentAccessGrantCreate struct {
	config
	mutation *DepartmentAccessGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *DepartmentAccessGrantCreate) SetUserID(v int64) *DepartmentAccessGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *DepartmentAccessGrantCreate) SetDepartmentID(v int64) *DepartmentAccessGrantCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DepartmentAccessGrantCreate) SetCreatedBy(v int64) *DepartmentAccessGrantCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DepartmentAccessGrantCreate) SetCreatedAt(v time.Time) *DepartmentAccessGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DepartmentAccessGrantCreate) SetNillableCreatedAt(v *time.Time) *DepartmentAccessGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DepartmentAccessGrantCreate) SetUser(v *User) *DepartmentAccessGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_c *DepartmentAccessGrantCreate) SetDepartment(v *Department) *DepartmentAccessGrantCreate {
	return _c.SetDepartmentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *DepartmentAccessGrantCreate) SetCreatorID(id int64) *DepartmentAccessGrantCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *DepartmentAccessGrantCreate) SetCreator(v *User) *DepartmentAccessGrantCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the DepartmentAccessGrantMutation object of the builder.
func (_c *DepartmentAccessGrantCreate) Mutation() *DepartmentAccessGrantMutation {
	return _c.mutation
}

// Save creates the DepartmentAccessGrant in the database.
func (_c *DepartmentAccessGrantCreate) Save(ctx context.Context) (*DepartmentAccessGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepartmentAccessGrantCreate) SaveX(ctx context.Context) *DepartmentAccessGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentAccessGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentAccessGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepartmentAccessGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := departmentaccessgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepartmentAccessGrantCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DepartmentAccessGrant.user_id"`)}
	}
	if _, ok := _c.mutation.DepartmentID(); !ok {
		return &ValidationError{Name: "department_id", err: errors.New(`ent: missing required field "DepartmentAccessGrant.department_id"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "DepartmentAccessGrant.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DepartmentAccessGrant.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DepartmentAccessGrant.user"`)}
	}
	if len(_c.mutation.DepartmentIDs()) == 0 {
		return &ValidationError{Name: "department", err: errors.New(`ent: missing required edge "DepartmentAccessGrant.department"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "DepartmentAccessGrant.creator"`)}
	}
	return nil
}

func (_c *DepartmentAccessGrantCreate) sqlSave(ctx context.Context) (*DepartmentAccessGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *DepartmentAccessGrantCreate) createSpec() (*DepartmentAccessGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &DepartmentAccessGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(departmentaccessgrant.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(departmentaccessgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.UserTable,
			Columns: []string{departmentaccessgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.DepartmentTable,
			Columns: []string{departmentaccessgrant.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.CreatorTable,
			Columns: []string{departmentaccessgrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DepartmentAccessGrant.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepartmentAccessGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DepartmentAccessGrantCreate) OnConflict(opts ...sql.ConflictOption) *DepartmentAccessGrantUpsertOne {
	_c.conflict = opts
	return &DepartmentAccessGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DepartmentAccessGrantCreate) OnConflictColumns(columns ...string) *DepartmentAccessGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DepartmentAccessGrantUpsertOne{
		create: _c,
	}
}

type (
	// DepartmentAccessGrantUpsertOne is the builder for "upsert"-ing
	//  one DepartmentAccessGrant node.
	DepartmentAccessGrantUpsertOne struct {
		create *DepartmentAccessGrantCreate
	}

	// DepartmentAccessGrantUpsert is the "OnConflict" setter.
	DepartmentAccessGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *DepartmentAccessGrantUpsert) SetUserID(v int64) *DepartmentAccessGrantUpsert {
	u.Set(departmentaccessgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsert) UpdateUserID() *DepartmentAccessGrantUpsert {
	u.SetExcluded(departmentaccessgrant.FieldUserID)
	return u
}

// SetDepartmentID sets the "department_id" field.
func (u *DepartmentAccessGrantUpsert) SetDepartmentID(v int64) *DepartmentAccessGrantUpsert {
	u.Set(departmentaccessgrant.FieldDepartmentID, v)
	return u
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsert) UpdateDepartmentID() *DepartmentAccessGrantUpsert {
	u.SetExcluded(departmentaccessgrant.FieldDepartmentID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DepartmentAccessGrantUpsert) SetCreatedBy(v int64) *DepartmentAccessGrantUpsert {
	u.Set(departmentaccessgrant.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsert) UpdateCreatedBy() *DepartmentAccessGrantUpsert {
	u.SetExcluded(departmentaccessgrant.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DepartmentAccessGrantUpsertOne) UpdateNewValues() *DepartmentAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(departmentaccessgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DepartmentAccessGrantUpsertOne) Ignore() *DepartmentAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepartmentAccessGrantUpsertOne) DoNothing() *DepartmentAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepartmentAccessGrantCreate.OnConflict
// documentation for more info.
func (u *DepartmentAccessGrantUpsertOne) Update(set func(*DepartmentAccessGrantUpsert)) *DepartmentAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepartmentAccessGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DepartmentAccessGrantUpsertOne) SetUserID(v int64) *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertOne) UpdateUserID() *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *DepartmentAccessGrantUpsertOne) SetDepartmentID(v int64) *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertOne) UpdateDepartmentID() *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateDepartmentID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DepartmentAccessGrantUpsertOne) SetCreatedBy(v int64) *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertOne) UpdateCreatedBy() *DepartmentAccessGrantUpsertOne {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *DepartmentAccessGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepartmentAccessGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepartmentAccessGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// DepartmentAccessGrantCreateBulk is the builder for creating many DepartmentAccessGrant entities in bulk.
type DepartmentAccessGrantCreateBulk struct {
	config
	err      error
	builders []*DepartmentAccessGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the DepartmentAccessGrant entities in the database.
func (_c *DepartmentAccessGrantCreateBulk) Save(ctx context.Context) ([]*DepartmentAccessGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DepartmentAccessGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepartmentAccessGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepartmentAccessGrantCreateBulk) SaveX(ctx context.Context) []*DepartmentAccessGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentAccessGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentAccessGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DepartmentAccessGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepartmentAccessGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DepartmentAccessGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *DepartmentAccessGrantUpsertBulk {
	_c.conflict = opts
	return &DepartmentAccessGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DepartmentAccessGrantCreateBulk) OnConflictColumns(columns ...string) *DepartmentAccessGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DepartmentAccessGrantUpsertBulk{
		create: _c,
	}
}

// DepartmentAccessGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of DepartmentAccessGrant nodes.
type DepartmentAccessGrantUpsertBulk struct {
	create *DepartmentAccessGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DepartmentAccessGrantUpsertBulk) UpdateNewValues() *DepartmentAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(departmentaccessgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DepartmentAccessGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DepartmentAccessGrantUpsertBulk) Ignore() *DepartmentAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepartmentAccessGrantUpsertBulk) DoNothing() *DepartmentAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepartmentAccessGrantCreateBulk.OnConflict
// documentation for more info.
func (u *DepartmentAccessGrantUpsertBulk) Update(set func(*DepartmentAccessGrantUpsert)) *DepartmentAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepartmentAccessGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DepartmentAccessGrantUpsertBulk) SetUserID(v int64) *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertBulk) UpdateUserID() *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *DepartmentAccessGrantUpsertBulk) SetDepartmentID(v int64) *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertBulk) UpdateDepartmentID() *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateDepartmentID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DepartmentAccessGrantUpsertBulk) SetCreatedBy(v int64) *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DepartmentAccessGrantUpsertBulk) UpdateCreatedBy() *DepartmentAccessGrantUpsertBulk {
	return u.Update(func(s *DepartmentAccessGrantUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *DepartmentAccessGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DepartmentAccessGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepartmentAccessGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepartmentAccessGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
