// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/departmentaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DepartmentAccessGrantUpdate is the builder for updating DepartmentAccessGrant entities.
type DepartmentAccessGrantUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentAccessGrantMutation
}

// Where appends a list predicates to the DepartmentAccessGrantUpdate builder.
func (_u *DepartmentAccessGrantUpdate) Where(ps ...predicate.DepartmentAccessGrant) *DepartmentAccessGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DepartmentAccessGrantUpdate) SetUserID(v int64) *DepartmentAccessGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdate) SetNillableUserID(v *int64) *DepartmentAccessGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *DepartmentAccessGrantUpdate) SetDepartmentID(v int64) *DepartmentAccessGrantUpdate {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdate) SetNillableDepartmentID(v *int64) *DepartmentAccessGrantUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DepartmentAccessGrantUpdate) SetCreatedBy(v int64) *DepartmentAccessGrantUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdate) SetNillableCreatedBy(v *int64) *DepartmentAccessGrantUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DepartmentAccessGrantUpdate) SetUser(v *User) *DepartmentAccessGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *DepartmentAccessGrantUpdate) SetDepartment(v *Department) *DepartmentAccessGrantUpdate {
	return _u.SetDepartmentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *DepartmentAccessGrantUpdate) SetCreatorID(id int64) *DepartmentAccessGrantUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *DepartmentAccessGrantUpdate) SetCreator(v *User) *DepartmentAccessGrantUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the DepartmentAccessGrantMutation object of the builder.
func (_u *DepartmentAccessGrantUpdate) Mutation() *DepartmentAccessGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DepartmentAccessGrantUpdate) ClearUser() *DepartmentAccessGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *DepartmentAccessGrantUpdate) ClearDepartment() *DepartmentAccessGrantUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *DepartmentAccessGrantUpdate) ClearCreator() *DepartmentAccessGrantUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepartmentAccessGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentAccessGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepartmentAccessGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentAccessGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentAccessGrantUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.user"`)
	}
	if _u.mutation.DepartmentCleared() && len(_u.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.department"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.creator"`)
	}
	return nil
}

func (_u *DepartmentAccessGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(departmentaccessgrant.Table, departmentaccessgrant.Columns, sqlgraph.NewFieldSpec(departmentaccessgrant.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(departmentaccessgrant.FieldDepartmentID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.UserTable,
			Columns: []string{departmentaccessgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.UserTable,
			Columns: []string{departmentaccessgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.DepartmentTable,
			Columns: []string{departmentaccessgrant.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.DepartmentTable,
			Columns: []string{departmentaccessgrant.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.CreatorTable,
			Columns: []string{departmentaccessgrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.CreatorTable,
			Columns: []string{departmentaccessgrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{departmentaccessgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepartmentAccessGrantUpdateOne is the builder for updating a single DepartmentAccessGrant entity.
type DepartmentAccessGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentAccessGrantMutation
}

// SetUserID sets the "user_id" field.
func (_u *DepartmentAccessGrantUpdateOne) SetUserID(v int64) *DepartmentAccessGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdateOne) SetNillableUserID(v *int64) *DepartmentAccessGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *DepartmentAccessGrantUpdateOne) SetDepartmentID(v int64) *DepartmentAccessGrantUpdateOne {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdateOne) SetNillableDepartmentID(v *int64) *DepartmentAccessGrantUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DepartmentAccessGrantUpdateOne) SetCreatedBy(v int64) *DepartmentAccessGrantUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DepartmentAccessGrantUpdateOne) SetNillableCreatedBy(v *int64) *DepartmentAccessGrantUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DepartmentAccessGrantUpdateOne) SetUser(v *User) *DepartmentAccessGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *DepartmentAccessGrantUpdateOne) SetDepartment(v *Department) *DepartmentAccessGrantUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *DepartmentAccessGrantUpdateOne) SetCreatorID(id int64) *DepartmentAccessGrantUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *DepartmentAccessGrantUpdateOne) SetCreator(v *User) *DepartmentAccessGrantUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the DepartmentAccessGrantMutation object of the builder.
func (_u *DepartmentAccessGrantUpdateOne) Mutation() *DepartmentAccessGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DepartmentAccessGrantUpdateOne) ClearUser() *DepartmentAccessGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *DepartmentAccessGrantUpdateOne) ClearDepartment() *DepartmentAccessGrantUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *DepartmentAccessGrantUpdateOne) ClearCreator() *DepartmentAccessGrantUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the DepartmentAccessGrantUpdate builder.
func (_u *DepartmentAccessGrantUpdateOne) Where(ps ...predicate.DepartmentAccessGrant) *DepartmentAccessGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepartmentAccessGrantUpdateOne) Select(field string, fields ...string) *DepartmentAccessGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DepartmentAccessGrant entity.
func (_u *DepartmentAccessGrantUpdateOne) Save(ctx context.Context) (*DepartmentAccessGrant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentAccessGrantUpdateOne) SaveX(ctx context.Context) *DepartmentAccessGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepartmentAccessGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentAccessGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentAccessGrantUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.user"`)
	}
	if _u.mutation.DepartmentCleared() && len(_u.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.department"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepartmentAccessGrant.creator"`)
	}
	return nil
}

func (_u *DepartmentAccessGrantUpdateOne) sqlSave(ctx context.Context) (_node *DepartmentAccessGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(departmentaccessgrant.Table, departmentaccessgrant.Columns, sqlgraph.NewFieldSpec(departmentaccessgrant.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(departmentaccessgrant.FieldDepartmentID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "DepartmentAccessGrant.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.DepartmentID(); !ok {
		return nil, &ValidationError{Name: "department_id", err: errors.New(`ent: missing "DepartmentAccessGrant.department_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !departmentaccessgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.UserTable,
			Columns: []string{departmentaccessgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.UserTable,
			Columns: []string{departmentaccessgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.DepartmentTable,
			Columns: []string{departmentaccessgrant.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.DepartmentTable,
			Columns: []string{departmentaccessgrant.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.CreatorTable,
			Columns: []string{departmentaccessgrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   departmentaccessgrant.CreatorTable,
			Columns: []string{departmentaccessgrant.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DepartmentAccessGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{departmentaccessgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
