// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/departmentaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DepartmentAccessGrantDelete is the builder for deleting a DepartmentAccessGrant entity.
type DepartmentAccessGrantDelete struct {
	config
	hooks    []Hook
	mutation *DepartmentAccessGrantMutation
}

// Where appends a list predicates to the DepartmentAccessGrantDelete builder.
func (_d *DepartmentAccessGrantDelete) Where(ps ...predicate.DepartmentAccessGrant) *DepartmentAccessGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DepartmentAccessGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DepartmentAccessGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DepartmentAccessGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(departmentaccessgrant.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DepartmentAccessGrantDeleteOne is the builder for deleting a single DepartmentAccessGrant entity.
type DepartmentAccessGrantDeleteOne struct {
	_d *DepartmentAccessGrantDelete
}

// Where appends a list predicates to the DepartmentAccessGrantDelete builder.
func (_d *DepartmentAccessGrantDeleteOne) Where(ps ...predicate.DepartmentAccessGrant) *DepartmentAccessGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DepartmentAccessGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{departmentaccessgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DepartmentAccessGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
