// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/departmentaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DepartmentAccessGrant is the model entity for the DepartmentAccessGrant schema.
type DepartmentAccessGrant struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID int64 `json:"department_id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepartmentAccessGrantQuery when eager-loading is set.
	Edges        DepartmentAccessGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DepartmentAccessGrantEdges holds the relations/edges for other nodes in the graph.
type DepartmentAccessGrantEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Department holds the value of the department edge.
	Department *Department `json:"department,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepartmentAccessGrantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DepartmentOrErr returns the Department value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepartmentAccessGrantEdges) DepartmentOrErr() (*Department, error) {
	if e.Department != nil {
		return e.Department, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: department.Label}
	}
	return nil, &NotLoadedError{edge: "department"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepartmentAccessGrantEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DepartmentAccessGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case departmentaccessgrant.FieldUserID, departmentaccessgrant.FieldDepartmentID, departmentaccessgrant.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case departmentaccessgrant.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DepartmentAccessGrant fields.
func (_m *DepartmentAccessGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case departmentaccessgrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case departmentaccessgrant.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = value.Int64
			}
		case departmentaccessgrant.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case departmentaccessgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DepartmentAccessGrant.
// This includes values selected through modifiers, order, etc.
func (_m *DepartmentAccessGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DepartmentAccessGrant entity.
func (_m *DepartmentAccessGrant) QueryUser() *UserQuery {
	return NewDepartmentAccessGrantClient(_m.config).QueryUser(_m)
}

// QueryDepartment queries the "department" edge of the DepartmentAccessGrant entity.
func (_m *DepartmentAccessGrant) QueryDepartment() *DepartmentQuery {
	return NewDepartmentAccessGrantClient(_m.config).QueryDepartment(_m)
}

// QueryCreator queries the "creator" edge of the DepartmentAccessGrant entity.
func (_m *DepartmentAccessGrant) QueryCreator() *UserQuery {
	return NewDepartmentAccessGrantClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this DepartmentAccessGrant.
// Note that you need to call DepartmentAccessGrant.Unwrap() before calling this method if this DepartmentAccessGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DepartmentAccessGrant) Update() *DepartmentAccessGrantUpdateOne {
	return NewDepartmentAccessGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DepartmentAccessGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DepartmentAccessGrant) Unwrap() *DepartmentAccessGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DepartmentAccessGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DepartmentAccessGrant) String() string {
	var builder strings.Builder
	builder.WriteString("DepartmentAccessGrant(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DepartmentAccessGrants is a parsable slice of DepartmentAccessGrant.
type DepartmentAccessGrants []*DepartmentAccessGrant
