import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import SubscriptionSelfResetPolicyDialog from '../SubscriptionSelfResetPolicyDialog.vue'

const mocks = vi.hoisted(() => ({ get: vi.fn(), put: vi.fn(), success: vi.fn() }))
vi.mock('@/api/subscriptionSelfReset', () => ({ getSelfResetPolicy: mocks.get, setSelfResetPolicy: mocks.put }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showSuccess: mocks.success }) }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const create = () => mount(SubscriptionSelfResetPolicyDialog, { global: { stubs: { BaseDialog: { template: '<div><slot /><slot name="footer" /></div>' } } } })
beforeEach(() => {
  vi.clearAllMocks()
  mocks.get.mockResolvedValue({ daily_limit_by_organization: { xunyou: 1, wsdashi: 2, other: 0 }, rollout: 'admin' })
  mocks.put.mockResolvedValue({})
})
describe('self reset policy settings', () => {
  it('loads authoritative values and saves all three organization limits', async () => {
    const wrapper = create()
    await flushPromises()
    const inputs = wrapper.findAll('input')
    expect(inputs.map(input => (input.element as HTMLInputElement).value)).toEqual(['1', '2', '0'])
    await inputs[0]!.setValue(3)
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.put).toHaveBeenCalledWith({ daily_limit_by_organization: { xunyou: 3, wsdashi: 2, other: 0 }, rollout: 'admin' })
    expect(wrapper.emitted('close')).toHaveLength(1)
    wrapper.unmount()
  })
  it('offers empty inputs, not invented defaults, to overwrite a policy that cannot be loaded', async () => {
    mocks.get.mockRejectedValue(new Error('corrupt policy'))
    const wrapper = create()
    await flushPromises()
    const inputs = wrapper.findAll('input')
    expect(inputs.map(input => (input.element as HTMLInputElement).value)).toEqual(['', '', ''])
    await wrapper.get('form').trigger('submit')
    expect(mocks.put).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('policyInvalid')
    await inputs[0]!.setValue(1)
    await inputs[1]!.setValue(1)
    await inputs[2]!.setValue(0)
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.put).toHaveBeenCalledWith({ daily_limit_by_organization: { xunyou: 1, wsdashi: 1, other: 0 }, rollout: 'admin' })
    wrapper.unmount()
  })
  it('rejects fractional values before saving', async () => {
    const wrapper = create()
    await flushPromises()
    await wrapper.get('input').setValue(1.5)
    await wrapper.get('form').trigger('submit')
    expect(mocks.put).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('policyInvalid')
    wrapper.unmount()
  })
})
