param(
    [switch]$SkipInstall,
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$LocalDir = Join-Path $RepoRoot ".localdev"
$LogsDir = Join-Path $LocalDir "logs"
$PidsDir = Join-Path $LocalDir "pids"
$BackendDataDir = Join-Path $LocalDir "backend-data"
$EnvFile = Join-Path $LocalDir "local-env.ps1"
$FrontendEnvFile = Join-Path (Join-Path $RepoRoot "frontend") ".env.local"
$BackendPidFile = Join-Path $PidsDir "backend.pid"
$FrontendPidFile = Join-Path $PidsDir "frontend.pid"
$BackendLog = Join-Path $LogsDir "backend.log"
$FrontendLog = Join-Path $LogsDir "frontend.log"

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Ensure-Dir([string]$Path) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Test-Command([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Test-TcpPort([string]$TargetHost, [int]$Port) {
    try {
        $client = [System.Net.Sockets.TcpClient]::new()
        $async = $client.BeginConnect($TargetHost, $Port, $null, $null)
        $connected = $async.AsyncWaitHandle.WaitOne(1000, $false)
        if (-not $connected) {
            $client.Close()
            return $false
        }
        $client.EndConnect($async)
        $client.Close()
        return $true
    } catch {
        return $false
    }
}

function Get-FreeTcpPort([int]$PreferredPort) {
    if (-not (Get-NetTCPConnection -LocalPort $PreferredPort -State Listen -ErrorAction SilentlyContinue)) {
        return $PreferredPort
    }

    $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, 0)
    $listener.Start()
    $port = ($listener.LocalEndpoint).Port
    $listener.Stop()
    return $port
}

function Stop-ProcessIfRunning([string]$PidFile) {
    if (-not (Test-Path $PidFile)) {
        return
    }

    $pidText = Get-Content $PidFile -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($pidText -and $pidText -match '^\d+$') {
        $proc = Get-Process -Id ([int]$pidText) -ErrorAction SilentlyContinue
        if ($proc) {
            cmd /d /c "taskkill /PID $($proc.Id) /T /F >nul 2>nul" | Out-Null
        }
    }

    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
}

function Stop-ProcessByPort([int]$Port) {
    $connections = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue
    foreach ($connection in ($connections | Select-Object -Unique OwningProcess)) {
        if ($connection.OwningProcess) {
            $proc = Get-Process -Id $connection.OwningProcess -ErrorAction SilentlyContinue
            if ($proc) {
                cmd /d /c "taskkill /PID $($proc.Id) /T /F >nul 2>nul" | Out-Null
            }
        }
    }
}

function Stop-ProcessByCommandPattern([string]$Pattern) {
    $targets = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $_.CommandLine -and $_.CommandLine -like "*$Pattern*"
    }
    foreach ($target in $targets) {
        cmd /d /c "taskkill /PID $($target.ProcessId) /T /F >nul 2>nul" | Out-Null
    }
}

function Rotate-LogIfExists([string]$LogPath) {
    if (-not (Test-Path $LogPath)) {
        return
    }

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $archivePath = "$LogPath.$timestamp"
    try {
        Move-Item -Path $LogPath -Destination $archivePath -Force
    } catch {
        Clear-Content -Path $LogPath -ErrorAction SilentlyContinue
    }
}

function Read-LocalEnv {
    $values = @{}
    if (-not (Test-Path $EnvFile)) {
        return $values
    }

    foreach ($line in Get-Content $EnvFile) {
        if ($line -match '^\s*\$env:([A-Za-z0-9_]+)\s*=\s*"(.*)"\s*$') {
            $values[$matches[1]] = ($matches[2] -replace '""', '"')
        }
    }

    return $values
}

function Write-LocalEnv([hashtable]$Values) {
    $lines = @(
        "# Generated by tools/start-local.ps1",
        "# Edit PostgreSQL credentials here if your local service does not use the defaults."
    )

    foreach ($key in ($Values.Keys | Sort-Object)) {
        $escaped = $Values[$key].Replace('"', '""')
        $lines += "`$env:$key = `"$escaped`""
    }

    Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
}

function New-RandomHex([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
}

function Wait-HttpReady([string]$Url, [int]$TimeoutSeconds) {
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        try {
            $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
                return $true
            }
        } catch {
        }
        Start-Sleep -Seconds 2
    } while ((Get-Date) -lt $deadline)

    return $false
}

function Start-DetachedProcess(
    [string]$FilePath,
    [string]$Arguments,
    [string]$WorkingDirectory
) {
    return Start-Process `
        -FilePath $FilePath `
        -ArgumentList $Arguments `
        -WorkingDirectory $WorkingDirectory `
        -PassThru `
        -WindowStyle Hidden
}

function Sync-LocalAdminPassword([hashtable]$Values) {
    Write-Step "Syncing local admin password"
    Push-Location (Join-Path $RepoRoot "backend")
    try {
        go run ./cmd/localadmin `
            -host 127.0.0.1 `
            -port 5432 `
            -user $Values["DATABASE_USER"] `
            -db-password $Values["DATABASE_PASSWORD"] `
            -dbname $Values["DATABASE_DBNAME"] `
            -sslmode $Values["DATABASE_SSLMODE"] `
            -email $Values["ADMIN_EMAIL"] `
            -password $Values["ADMIN_PASSWORD"]
        if ($LASTEXITCODE -ne 0) {
            throw "failed to sync local admin password"
        }
    } finally {
        Pop-Location
    }
}

function Sync-BackendServerConfig([string]$ServerHost, [int]$ServerPort) {
    $configPath = Join-Path $BackendDataDir "config.yaml"
    if (-not (Test-Path $configPath)) {
        return
    }

    $lines = Get-Content $configPath
    $inServer = $false
    $updated = foreach ($line in $lines) {
        if ($line -match '^server:\s*$') {
            $inServer = $true
            $line
            continue
        }

        if ($inServer -and $line -match '^\S') {
            $inServer = $false
        }

        if ($inServer -and $line -match '^(\s*)host:\s*.*$') {
            "$($matches[1])host: $ServerHost"
            continue
        }

        if ($inServer -and $line -match '^(\s*)port:\s*.*$') {
            "$($matches[1])port: $ServerPort"
            continue
        }

        $line
    }

    Set-Content -Path $configPath -Value $updated -Encoding UTF8
}

Ensure-Dir $LocalDir
Ensure-Dir $LogsDir
Ensure-Dir $PidsDir
Ensure-Dir $BackendDataDir

Write-Step "Checking local prerequisites"

if (-not (Test-Command "go")) {
    throw "Missing 'go' in PATH."
}

if (-not (Test-Command "node")) {
    throw "Missing 'node' in PATH."
}

if (-not (Test-Command "corepack")) {
    throw "Missing 'corepack' in PATH."
}

if (-not (Test-TcpPort "127.0.0.1" 5432)) {
    throw "Local PostgreSQL is not reachable on 127.0.0.1:5432."
}

if (-not (Test-TcpPort "127.0.0.1" 6379)) {
    throw "Local Redis/Memurai is not reachable on 127.0.0.1:6379."
}

$envValues = Read-LocalEnv
if (-not $envValues.ContainsKey("DATABASE_USER")) {
    $envValues["DATABASE_USER"] = "postgres"
}
if (-not $envValues.ContainsKey("DATABASE_PASSWORD")) {
    $envValues["DATABASE_PASSWORD"] = "postgres"
}
if (-not $envValues.ContainsKey("DATABASE_DBNAME")) {
    $envValues["DATABASE_DBNAME"] = "sub2api"
}
if (-not $envValues.ContainsKey("DATABASE_SSLMODE")) {
    $envValues["DATABASE_SSLMODE"] = "disable"
}
if (-not $envValues.ContainsKey("REDIS_PASSWORD")) {
    $envValues["REDIS_PASSWORD"] = ""
}
if (-not $envValues.ContainsKey("REDIS_DB")) {
    $envValues["REDIS_DB"] = "0"
}
if (-not $envValues.ContainsKey("ADMIN_EMAIL")) {
    $envValues["ADMIN_EMAIL"] = "admin@sub2api.local"
}
if (-not $envValues.ContainsKey("ADMIN_PASSWORD")) {
    $envValues["ADMIN_PASSWORD"] = New-RandomHex 12
}
if (-not $envValues.ContainsKey("JWT_SECRET")) {
    $envValues["JWT_SECRET"] = New-RandomHex 32
}
if (-not $envValues.ContainsKey("TOTP_ENCRYPTION_KEY")) {
    $envValues["TOTP_ENCRYPTION_KEY"] = New-RandomHex 32
}
if (-not $envValues.ContainsKey("RUN_MODE")) {
    $envValues["RUN_MODE"] = "standard"
}
if (-not $envValues.ContainsKey("TZ")) {
    $envValues["TZ"] = "Asia/Shanghai"
}
if (-not $envValues.ContainsKey("SERVER_HOST")) {
    $envValues["SERVER_HOST"] = "0.0.0.0"
}

Write-Step "Stopping stale local processes"
Stop-ProcessIfRunning $BackendPidFile
Stop-ProcessIfRunning $FrontendPidFile
Stop-ProcessByPort 8080
Stop-ProcessByPort 3000
Stop-ProcessByCommandPattern "go run ./cmd/server"
Stop-ProcessByCommandPattern "vite.js"
Stop-ProcessByCommandPattern "pnpm run dev --host 127.0.0.1"

$backendPort = Get-FreeTcpPort 8080
$frontendPort = Get-FreeTcpPort 3000
$envValues["SERVER_PORT"] = [string]$backendPort
$envValues["FRONTEND_PORT"] = [string]$frontendPort
$envValues["LOCAL_INFRA_MODE"] = "existing"

Write-LocalEnv $envValues
Sync-BackendServerConfig $envValues["SERVER_HOST"] $backendPort

Write-Step "Installing frontend package manager"
corepack enable | Out-Null
corepack prepare pnpm@10.23.0 --activate | Out-Null

if (-not $SkipInstall) {
    Write-Step "Installing frontend dependencies"
    Push-Location (Join-Path $RepoRoot "frontend")
    try {
        corepack pnpm install
        if ($LASTEXITCODE -ne 0) {
            throw "pnpm install failed."
        }
    } finally {
        Pop-Location
    }
}

Write-Step "Preparing frontend dev environment"
$frontendEnvLines = @(
    "VITE_DEV_PROXY_TARGET=http://127.0.0.1:$backendPort",
    "VITE_DEV_PORT=$frontendPort"
)
Set-Content -Path $FrontendEnvFile -Value $frontendEnvLines -Encoding UTF8

Write-Step "Starting backend"
Rotate-LogIfExists $BackendLog

$backendArgs = @(
    "/d",
    "/c",
    "set DATA_DIR=$BackendDataDir&& set AUTO_SETUP=true&& set SERVER_HOST=$($envValues['SERVER_HOST'])&& set SERVER_PORT=$backendPort&& set SERVER_MODE=debug&& set RUN_MODE=$($envValues['RUN_MODE'])&& set DATABASE_HOST=127.0.0.1&& set DATABASE_PORT=5432&& set DATABASE_USER=$($envValues['DATABASE_USER'])&& set DATABASE_PASSWORD=$($envValues['DATABASE_PASSWORD'])&& set DATABASE_DBNAME=$($envValues['DATABASE_DBNAME'])&& set DATABASE_SSLMODE=$($envValues['DATABASE_SSLMODE'])&& set REDIS_HOST=127.0.0.1&& set REDIS_PORT=6379&& set REDIS_PASSWORD=$($envValues['REDIS_PASSWORD'])&& set REDIS_DB=$($envValues['REDIS_DB'])&& set ADMIN_EMAIL=$($envValues['ADMIN_EMAIL'])&& set ADMIN_PASSWORD=$($envValues['ADMIN_PASSWORD'])&& set JWT_SECRET=$($envValues['JWT_SECRET'])&& set TOTP_ENCRYPTION_KEY=$($envValues['TOTP_ENCRYPTION_KEY'])&& set TZ=$($envValues['TZ'])&& go run ./cmd/server >> ""$BackendLog"" 2>&1"
) -join " "

$backendProc = Start-DetachedProcess `
    -FilePath "cmd.exe" `
    -Arguments $backendArgs `
    -WorkingDirectory (Join-Path $RepoRoot "backend")

Set-Content -Path $BackendPidFile -Value $backendProc.Id -Encoding ASCII

if (-not (Wait-HttpReady -Url "http://127.0.0.1:$backendPort/health" -TimeoutSeconds 120)) {
    throw "Backend did not become ready. Check $BackendLog"
}

Sync-LocalAdminPassword $envValues

Write-Step "Starting frontend"
Rotate-LogIfExists $FrontendLog

$frontendArgs = "/d /c corepack pnpm run dev --host 0.0.0.0 --port $frontendPort >> ""$FrontendLog"" 2>&1"
$frontendProc = Start-DetachedProcess `
    -FilePath "cmd.exe" `
    -Arguments $frontendArgs `
    -WorkingDirectory (Join-Path $RepoRoot "frontend")

Set-Content -Path $FrontendPidFile -Value $frontendProc.Id -Encoding ASCII

if (-not (Wait-HttpReady -Url "http://127.0.0.1:$frontendPort" -TimeoutSeconds 120)) {
    throw "Frontend did not become ready. Check $FrontendLog"
}

Write-Step "Local environment is ready"
$lanIPv4 = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -like "192.168.*" -or $_.IPAddress -like "10.*" -or $_.IPAddress -like "172.*" } |
    Select-Object -First 1 -ExpandProperty IPAddress)
Write-Host ""
Write-Host "Frontend: http://127.0.0.1:$frontendPort"
Write-Host "Backend : http://127.0.0.1:$backendPort"
if ($lanIPv4) {
    Write-Host "LAN API : http://$lanIPv4`:$backendPort"
}
Write-Host "Admin   : $($envValues['ADMIN_EMAIL'])"
Write-Host "Password: $($envValues['ADMIN_PASSWORD'])"
Write-Host "Logs    : $LogsDir"
Write-Host "Env     : $EnvFile"
Write-Host ""

if (-not $NoBrowser) {
    Start-Process "http://127.0.0.1:$frontendPort"
}
